--INSERT INTO CATEGORY (id, description) VALUES (Comic Books')
--INSERT INTO CATEGORY (id, description) VALUES ('Movies')
--INSERT INTO CATEGORY (id, description) VALUES ('Books')
--
--
--INSERT INTO Supplier (id, name) VALUES ('Panini Comics')
--INSERT INTO Supplier (id, name) VALUES ('Amazon')
--INSERT INTO Supplier (id, name) VALUES ('Livraria Online')
--
--
--INSERT INTO Product (name, fk_category, fk_supplier, quantity_available) VALUES ('Crise nas infinitas terras',1,1,10)
--INSERT INTO Product (name,fk_category,fk_supplier,quantity_available) VALUES ('Naruto',2,2,20)
--INSERT INTO Product (name,fk_category,fk_supplier ,quantity_available) VALUES ('One Puch Man',3,3,100)